apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: baseline
  namespace: ${NS}
spec:
  podSelector: {}
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
    - from:
        - podSelector: {}